name: Api Mongoose v1  #Nombre de Workflow

on: 
  push: #Cuando se ejecuta el wokflow
    branches:
      -master

jobs:
#Stages -> Procesos de CI que realiza el workflow

  build: #Compilar 
    runs-on: ubuntu-latest
    steps:
    #Pasos a realizar para que build funcione
    - uses: actions/checkout@v2 #Version de gitgub actios que se ocupa
    - name: Login al Heroku Registry  #Nombre del paso en que estas
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login #Ejecuta el comando especificado
    - name: Build & push de mi imagen
      env:
         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
           docker build . --tag api-mongoose-v1 -f /docker/prod/Dockerfile 
           docker tag api-mongoose-v1 registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
           docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
    - name: Release
     env:
         HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_API_KEY }} web

  test: #Test
    runs-on: ubuntu-latest
    steps:
    #Pasos a realizar para que build funcione
    - uses: actions/checkout@v2 #Version de gitgub action que se ocupa
    - name: Test API  #Nombre del paso en que estas
      uses: actions/setup-node@v2 
      with: 
        node-version: '14.x'
    - run: npm ci 
    - run: npm test
