name: Api Mongoose v1  #Nombre de Workflow

on: [push] #Cuando se ejecuta el wokflow

jobs:
#Stages -> Procesos de CI que realiza el workflow

  build: #Compilar 
    runs-on: ubuntu-latest
    steps:
    #Pasos a realizar para que build funcione
    - uses: actions/checkout@v2 #Version de gitgub actios que se ocupa
    - name: Build image Docker  #Nombre del paso en que estas
    - run: docker build . --file Dockerfile --tag api-mongoose-v1 #Ejecuta el comando especificado

  test: #Test
    runs-on: ubuntu-latest
    steps:
    #Pasos a realizar para que build funcione
    - uses: actions/checkout@v2 #Version de gitgub action que se ocupa
    - name: Test API  #Nombre del paso en que estas
    - uses: actions/setup-node@v2 
    - with: 
        node-version: '14.x'
    - run: npm ci 
    - run: npm test
